### PR TITLE
[NEW BRANCH fix-0.0.1.2021.12.28] Fix installation of version (for check_process)

### PR DESCRIPTION
**Pull request by fflorent**
## Problem

- the upgrades from previous versions fail at the installation of these version (git is not happy)

## Solution

- use `ynh_exec_as $app git`

IMPORTANT: Please do not merge, just create a new one based with this commit at the HEAD.

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by yalh76** [comment]
> 
> IMPORTANT: Please do not merge, just create a new one based with this commit at the HEAD.


How to do that ?

**Comment by fflorent** [comment]
> How to do that ?

```bash
gh repo set-default git@github.com:YunoHost-Apps/peertube-search-index_ynh.git
gh pr checkout 33
git push -u origin
```

**Comment by fflorent** [comment]
Please, there is no need to run the tests, just execute the above commands.

**Comment by yalh76** [comment]
> Please, there is no need to run the tests, just execute the above commands to push in a dedicated branch.

But what we do for currently installed peertube-search-index_ynh if they can't be upgraded ?

**Comment by fflorent** [comment]
> But what we do for currently installed peertube-search-index_ynh if they can't be upgraded ?

Already installed instances are fine because `git` did not caused the problem while installing. If you take a look at the failures, you'll see that the problem is the preliminary installation:

```
 > Preliminary install...

/tmp/package_check.fLSsnm/app_folder /var/www/yunorunner/package_check
/var/www/yunorunner/package_check
Running: yunohost app install --force /app_folder -a "domain=sub.domain.tld&is_public=1&path=/&admin=package_checker&init_main_permission=visitors&"
2716 INFO Installing peertube-search-index...
3311 INFO [+...................] > Validating installation parameters...
4613 INFO [#+..................] > Storing installation settings...
5449 INFO [##+.................] > Finding an available port...
6074 INFO [###++...............] > Installing dependencies...
153343 INFO [#####+..............] > Configuring system user... [2.4 minutes]
153957 INFO [######+.............] > Setting up source files...
155747 INFO [#######+............] > Configuring NGINX web server...
161033 INFO [########++..........] > Building...
161112 WARNING fatal: detected dubious ownership in repository at '/var/www/peertube-search-index'
161113 WARNING To add an exception for this directory, call:
161121 WARNING 	git config --global --add safe.directory /var/www/peertube-search-index
162618 ERROR Unable to install peertube-search-index: An error occurred inside the app installation script
162619 INFO The operation 'Install the 'peertube-search-index' app' could not be completed. Please share the full log of this operation using the command 'yunohost log share 20230319-104455-app_install-peertube-search-index' to get help
162697 WARNING Here's an extract of the logs before the crash. It might help debugging the error:
162697 INFO DEBUG - + line_match=
162697 INFO DEBUG - + length=20
162697 INFO DEBUG - + log_path=/var/log/nginx/nginx.log
162698 INFO DEBUG - + timeout=300
162698 INFO DEBUG - + '[' reload == stop ']'
162698 INFO DEBUG - + '[' reload == reload ']'
162698 INFO DEBUG - + action=reload-or-restart
162698 INFO DEBUG - ++ date --utc --rfc-3339=seconds
162699 INFO DEBUG - ++ cut -d+ -f1
162699 INFO DEBUG - + local 'time_start=2023-03-19 10:47:33 UTC'
162699 INFO DEBUG - + systemctl reload-or-restart nginx
162699 INFO INFO - [########++..........] > Building...
162699 INFO DEBUG - + pushd /var/www/peertube-search-index
162699 INFO DEBUG - /var/www/peertube-search-index /var/cache/yunohost/app_tmp_work_dirs/app_200b7uz3/app_folder/scripts
162699 INFO DEBUG - + git submodule update --init --recursive
162699 INFO WARNING - fatal: detected dubious ownership in repository at '/var/www/peertube-search-index'
162699 INFO WARNING - To add an exception for this directory, call:
162699 INFO DEBUG -
162699 INFO WARNING - 	git config --global --add safe.directory /var/www/peertube-search-index
162699 INFO DEBUG - + ynh_exit_properly
162742 WARNING Removing the app after installation failure...
163141 INFO [++..................] > Loading installation settings...
164464 INFO [##++................] > Stopping and removing the systemd service...
164608 INFO [####++..............] > Removing dependencies...
172819 INFO [######++............] > Removing app main directory...
173103 INFO [########+++.........] > Removing NGINX web server configuration...
173869 INFO [###########++.......] > Removing logrotate configuration...
174037 INFO [#############++.....] > Removing the dedicated system user...
174633 INFO [###############++...] > Removal of peertube-search-index completed
177750 ERROR The operation 'Install the 'peertube-search-index' app' could not be completed. Please share the full log of this operation using the command 'yunohost log share 20230319-104455-app_install-peertube-search-index' to get help
```

**Pull request closed without merging**
