### PR TITLE
[NEW BRANCH fix-0.0.1.2023.08.08] Fix installation of version (for check_process)

### PR DESCRIPTION
**Pull request by fflorent**
## Problem

- the upgrades from previous versions fail at the installation of these version (git is not happy)

## Solution

- use `ynh_exec_as $app git`

IMPORTANT: Please do not merge, just create a new one based with this commit at the HEAD.

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by yalh76** [comment]
> 
> IMPORTANT: Please do not merge, just create a new one based with this commit at the HEAD.


How to do that ?

**Comment by fflorent** [comment]
> How to do that ?

```bash
gh repo set-default git@github.com:YunoHost-Apps/peertube-search-index_ynh.git
gh pr checkout 34
git push -u origin
```

**Comment by ericgaspar** [comment]
!testme

**Comment by yalh76** [comment]
!testme

**Comment by fflorent** [comment]
Please see https://github.com/YunoHost-Apps/peertube-search-index_ynh/pull/33#issuecomment-1658970184

**Comment by fflorent** [comment]
Please, no, merge like this way:
https://github.com/YunoHost-Apps/peertube-search-index_ynh/pull/34#issuecomment-1436967155

**Pull request merged**
