### PR TITLE
[NEW BRANCH fix-0.0.1.2023.08.08] Fix installation of version (for check_process)

### PR DESCRIPTION
**Pull request by yalh76**
## Problem

- the upgrades from previous versions fail at the installation of these version (git is not happy)

## Solution

- use `ynh_exec_as $app git`

IMPORTANT: Please do not merge, just create a new one based with this commit at the HEAD.

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by yalh76** [comment]
!testme
!bookwormtestme

**Comment by fflorent** [comment]
Please, we don't understand each others. Refer to my intent here, and tell me if you have questions:
https://github.com/YunoHost-Apps/peertube-search-index_ynh/pull/34#issuecomment-1436967155

This is not meant to be merged into master

**Comment by yalh76** [comment]
> Please, we don't understand each others. Refer to my intent here, and tell me if you have questions: [#34 (comment)](https://github.com/YunoHost-Apps/peertube-search-index_ynh/pull/34#issuecomment-1436967155)
> 
> This is not meant to be merged into master

Why not merging ? 
I don't understand why not.

**Comment by fflorent** [comment]
Alright, that seems to work. The elasticsearch (ES) client required by peertube-search-index is for version 8, the ES version installed here is 7.

I made this PR a while ago, I don't have news: https://github.com/YunoHost-Apps/peertube-search-index_ynh/pull/32

This notably upgrades ES to version 8 and take advantage of the packaging of https://github.com/YunoHost-Apps/elasticsearch8_ynh

This patch was meant to make the test run for this PR.

If the PR I proposed is not relevant, I would close it.

**Pull request merged**
